export type BgColorScheme = "light" | "dark";

export type BgColorRole =
  | "screen"
  | "screenAlt"
  | "screenSubtle"
  | "card"
  | "cardElevated"
  | "cardSubtle"
  | "heroCard"
  | "heroCardPanel"
  | "surface"
  | "surfaceElevated"
  | "input"
  | "inputFilled"
  | "inputAlt"
  | "separator"
  | "divider"
  | "sectionDividerLine"
  | "sectionAccentLine"
  | "overlay"
  | "tabInactive"
  | "tabActiveBg"
  | "accent"
  | "accentSoft"
  | "accentBlue"
  | "accentBlueSoft"
  | "accentGreen"
  | "accentGreenSoft"
  | "accentGreenDeep"
  | "accentOrange"
  | "accentOrangeSoft"
  | "accentPurple"
  | "accentPurpleSoft"
  | "accentRed"
  | "accentRedSoft"
  | "accentRedDeep"
  | "dangerSoft"
  | "dangerStrong"
  | "successSoft"
  | "subtleGray"
  | "subtleGrayLight"
  | "verifyEmailCard"
  | "countersAccentBg"
  | "countersStatCard1"
  | "countersStatCard2"
  | "greetingsAccentBg"
  | "greetingsStatCard1"
  | "greetingsStatCard2"
  | "prenominalAccentBg"
  | "passwordStrengthFair"
  | "transparent";

export type BgColorTokens = Record<BgColorRole, string>;

export const BackgroundColors: Record<BgColorScheme, BgColorTokens> = {
  light: {
    screen: "#fff",
    screenAlt: "#F2F2F7",
    screenSubtle: "#f5f5f5",
    card: "#fff",
    cardElevated: "#F9F9F9",
    cardSubtle: "#f5f5f5",
    heroCard: "#f8fafc",
    heroCardPanel: "#fff",
    surface: "#fff",
    surfaceElevated: "#fff",
    input: "#F5F7FA",
    inputFilled: "#f5f5f5",
    inputAlt: "#F2F2F7",
    separator: "#E5E5EA",
    divider: "#c6c6c8",
    sectionDividerLine: "rgba(17,24,39,0.1)",
    sectionAccentLine: "#2563eb",
    overlay: "rgba(0,0,0,0.5)",
    tabInactive: "#F2F2F7",
    tabActiveBg: "#111827",
    accent: "#007AFF",
    accentSoft: "#e7f0ff",
    accentBlue: "#007AFF",
    accentBlueSoft: "#E6F2FF",
    accentGreen: "#34C759",
    accentGreenSoft: "#f0fdf4",
    accentGreenDeep: "#E8F7EC",
    accentOrange: "#FF9500",
    accentOrangeSoft: "#F0F0F0",
    accentPurple: "#a78bfa",
    accentPurpleSoft: "#ddd6fe",
    accentRed: "#FF3B30",
    accentRedSoft: "#FFF5F5",
    accentRedDeep: "#FFF1F1",
    dangerSoft: "#FEE",
    dangerStrong: "#d92d20",
    successSoft: "#F0FFF4",
    subtleGray: "#E0E0E0",
    subtleGrayLight: "#F0F0F0",
    verifyEmailCard: "#f1f5f9",
    countersAccentBg: "#dbeafe",
    countersStatCard1: "#60a5fa",
    countersStatCard2: "#bfdbfe",
    greetingsAccentBg: "#ffedd5",
    greetingsStatCard1: "#fb923c",
    greetingsStatCard2: "#fdba74",
    prenominalAccentBg: "#ede9fe",
    passwordStrengthFair: "#FF9500",
    transparent: "transparent",
  },
  dark: {
    screen: "#000",
    screenAlt: "#000",
    screenSubtle: "#1c1c1e",
    card: "#1c1c1e",
    cardElevated: "#1C1C1E",
    cardSubtle: "#1c1c1e",
    heroCard: "#111827",
    heroCardPanel: "#121318",
    surface: "#1c1c1e",
    surfaceElevated: "#1c1c1e",
    input: "#121212",
    inputFilled: "#1c1c1e",
    inputAlt: "#3A3A3C",
    separator: "#3A3A3C",
    divider: "#38383a",
    sectionDividerLine: "rgba(255,255,255,0.12)",
    sectionAccentLine: "#8ab4ff",
    overlay: "rgba(0,0,0,0.7)",
    tabInactive: "#1C1C1E",
    tabActiveBg: "#fff",
    accent: "#007AFF",
    accentSoft: "#14304d",
    accentBlue: "#007AFF",
    accentBlueSoft: "#0A1F3D",
    accentGreen: "#34C759",
    accentGreenSoft: "#06201b",
    accentGreenDeep: "#113A1A",
    accentOrange: "#FF9500",
    accentOrangeSoft: "#333",
    accentPurple: "#7c3aed",
    accentPurpleSoft: "#5b21b6",
    accentRed: "#FF3B30",
    accentRedSoft: "#2C1618",
    accentRedDeep: "#2A1414",
    dangerSoft: "#2C1618",
    dangerStrong: "#d92d20",
    successSoft: "#0F2410",
    subtleGray: "#333",
    subtleGrayLight: "#333",
    verifyEmailCard: "#1e293b",
    countersAccentBg: "#1e3a5f",
    countersStatCard1: "#2563eb",
    countersStatCard2: "#1d4ed8",
    greetingsAccentBg: "#3f2a12",
    greetingsStatCard1: "#f97316",
    greetingsStatCard2: "#ea580c",
    prenominalAccentBg: "#2d1f5e",
    passwordStrengthFair: "#FF9500",
    transparent: "transparent",
  },
};

export const getBackgroundColors = (isDark: boolean): BgColorTokens =>
  BackgroundColors[isDark ? "dark" : "light"];
