export type FontColorScheme = "light" | "dark";

export type FontColorRole =
  | "primary"
  | "secondary"
  | "muted"
  | "subtle"
  | "example"
  | "translation"
  | "furigana"
  | "body"
  | "supporting"
  | "tertiary"
  | "placeholder"
  | "error"
  | "success"
  | "link"
  | "sectionMeta"
  | "iconMuted"
  | "inverse"
  | "transparent"
  | "screenTitle"
  | "screenTitleCompact"
  | "screenTitleStrong"
  | "screenBodyStrong"
  | "screenMuted"
  | "screenMutedStrong"
  | "screenMutedCool"
  | "screenMetaCool"
  | "tablePrimary"
  | "actionAccent"
  | "actionAccentStrong"
  | "dangerAction"
  | "dangerText"
  | "successText"
  | "quizCorrect"
  | "buttonOnAccent"
  | "selectedOnLight"
  | "kanaRomaji"
  | "kanaRomajiActive"
  | "heroSubtitle"
  | "sectionLabelSoft"
  | "sectionSubtitle"
  | "countersAccentText"
  | "greetingsAccentText"
  | "prenominalAccentText"
  | "deviceHelper"
  | "deviceMeta"
  | "verifyEmailValue"
  | "authErrorTitle"
  | "authErrorMessage"
  | "passwordResetSuccessText"
  | "passwordStrengthFair"
  | "iconSubtle"
  | "iconMutedOverlay"
  | "inputPlaceholderDim"
  | "iconBlue"
  | "iconGreenSuccess"
  | "iconError"
  | "mutedLabel"
  | "inputBorder"
  | "inputBorderError"
  | "inputBorderSuccess"
  | "inputBorderErrorSoft"
  | "cardBorder"
  | "successBorder"
  | "successBorderAlt"
  | "errorBannerBorder"
  | "avatarBorder"
  | "surfaceBorder";

export type FontColorTokens = Record<FontColorRole, string>;

export const FontColors: Record<FontColorScheme, FontColorTokens> = {
  light: {
    primary: "#1a1a1a",
    secondary: "#1a1a1a",
    muted: "#666",
    subtle: "#666",
    example: "#555",
    translation: "#888",
    furigana: "#999",
    body: "#333",
    supporting: "#666",
    tertiary: "#999",
    placeholder: "#999",
    error: "#DC3545",
    success: "green",
    link: "#007AFF",
    sectionMeta: "#6e6e73",
    iconMuted: "#666",
    inverse: "#fff",
    transparent: "transparent",
    screenTitle: "#000",
    screenTitleCompact: "#111",
    screenTitleStrong: "#111827",
    screenBodyStrong: "#333",
    screenMuted: "#6e6e73",
    screenMutedStrong: "#666",
    screenMutedCool: "#4b5563",
    screenMetaCool: "#94a3b8",
    tablePrimary: "#2a3437",
    actionAccent: "#007AFF",
    actionAccentStrong: "#1f5fbf",
    dangerAction: "#FF3B30",
    dangerText: "#b3261e",
    successText: "#15803d",
    quizCorrect: "#34C759",
    buttonOnAccent: "#fff",
    selectedOnLight: "#fff",
    kanaRomaji: "rgba(0,0,0,0.38)",
    kanaRomajiActive: "rgba(255,255,255,0.75)",
    heroSubtitle: "rgba(17,24,39,0.65)",
    sectionLabelSoft: "rgba(17,24,39,0.5)",
    sectionSubtitle: "rgba(17,24,39,0.55)",
    countersAccentText: "#1d4ed8",
    greetingsAccentText: "#c2410c",
    prenominalAccentText: "#6d28d9",
    deviceHelper: "#666",
    deviceMeta: "#555",
    verifyEmailValue: "#1e293b",
    authErrorTitle: "#D93025",
    authErrorMessage: "#8A1C1C",
    passwordResetSuccessText: "#1D6B2F",
    passwordStrengthFair: "#FF9500",
    iconSubtle: "#c7c7cc",
    iconMutedOverlay: "rgba(0,0,0,0.3)",
    inputPlaceholderDim: "rgba(0,0,0,0.35)",
    iconBlue: "#2563eb",
    iconGreenSuccess: "#166534",
    iconError: "#D93025",
    mutedLabel: "#666",
    inputBorder: "#E0E0E0",
    inputBorderError: "#DC3545",
    inputBorderSuccess: "#28A745",
    inputBorderErrorSoft: "#FCC",
    cardBorder: "#e2e8f0",
    successBorder: "#bbf7d0",
    successBorderAlt: "#9CD7AC",
    errorBannerBorder: "#F5B5B5",
    avatarBorder: "#FFF",
    surfaceBorder: "#FFF",
  },
  dark: {
    primary: "#fff",
    secondary: "#e0e0e0",
    muted: "#999",
    subtle: "#aaa",
    example: "#aaa",
    translation: "#777",
    furigana: "#888",
    body: "#fff",
    supporting: "#ccc",
    tertiary: "#888",
    placeholder: "#666",
    error: "#FF6B6B",
    success: "green",
    link: "#007AFF",
    sectionMeta: "#8e8e93",
    iconMuted: "#888",
    inverse: "#fff",
    transparent: "transparent",
    screenTitle: "#fff",
    screenTitleCompact: "#fff",
    screenTitleStrong: "#fff",
    screenBodyStrong: "#fff",
    screenMuted: "#8e8e93",
    screenMutedStrong: "#AAA",
    screenMutedCool: "#94a3b8",
    screenMetaCool: "#64748b",
    tablePrimary: "#fff",
    actionAccent: "#007AFF",
    actionAccentStrong: "#8ab4ff",
    dangerAction: "#FF3B30",
    dangerText: "#ffb4ab",
    successText: "#a7f3d0",
    quizCorrect: "#34C759",
    buttonOnAccent: "#fff",
    selectedOnLight: "#111827",
    kanaRomaji: "rgba(255,255,255,0.4)",
    kanaRomajiActive: "rgba(255,255,255,0.75)",
    heroSubtitle: "rgba(255,255,255,0.66)",
    sectionLabelSoft: "rgba(255,255,255,0.54)",
    sectionSubtitle: "rgba(255,255,255,0.6)",
    countersAccentText: "#c6dbff",
    greetingsAccentText: "#fed7aa",
    prenominalAccentText: "#c4b5fd",
    deviceHelper: "#c7c7cc",
    deviceMeta: "#c7c7cc",
    verifyEmailValue: "#fff",
    authErrorTitle: "#FFB3B3",
    authErrorMessage: "#FFD5D5",
    passwordResetSuccessText: "#B8F5C4",
    passwordStrengthFair: "#FF9500",
    iconSubtle: "#555",
    iconMutedOverlay: "rgba(255,255,255,0.4)",
    inputPlaceholderDim: "rgba(255,255,255,0.4)",
    iconBlue: "#3b82f6",
    iconGreenSuccess: "#a7f3d0",
    iconError: "#FF8A8A",
    mutedLabel: "#888",
    inputBorder: "#333",
    inputBorderError: "#5C2B2E",
    inputBorderSuccess: "#1E4620",
    inputBorderErrorSoft: "#5C2B2E",
    cardBorder: "#1f2937",
    successBorder: "#064e3b",
    successBorderAlt: "#1F6A2F",
    errorBannerBorder: "#5C1F1F",
    avatarBorder: "#333",
    surfaceBorder: "#1C1C1E",
  },
};

export const getFontColors = (isDark: boolean): FontColorTokens =>
  FontColors[isDark ? "dark" : "light"];
